import { ProductCategory, SubProduct } from './types';

export const productCategories: ProductCategory[] = [
  // ================================================================
  // 1. GROUNDNUTS
  // ================================================================
  {
    name: 'Groundnuts',
    slug: 'groundnuts',
    image: '/images/products/groundnuts.png',
    description: 'AGRITRADE OVERSEAS is a trusted supplier of premium Indian groundnuts sourced from Gujarat\'s most fertile farming regions. We offer a comprehensive range of groundnut varieties — from raw in-shell peanuts to blanched and specialty types — processed under strict quality controls and packaged for export to international markets across the Middle East, Southeast Asia, Europe, and Africa.',
    metaTitle: 'Premium Groundnuts Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian groundnuts in multiple varieties. Peanuts In Shell, Blanched, Bold & Java Peanuts from Gujarat. Premium sourcing and export-ready packaging.',
    subProducts: [
      {
        name: 'Peanuts In Shell',
        slug: 'peanuts-in-shell',
        image: '/images/products/groundnuts/peanuts-in-shell.png',
        shortDescription: 'Premium quality raw peanuts in shell, carefully harvested and dried for maximum freshness and extended shelf life.',
        fullDescription: 'AGRITRADE OVERSEAS supplies premium-grade Peanuts In Shell sourced directly from Gujarat\'s leading groundnut farming regions. Our in-shell peanuts are carefully selected at harvest, naturally sun-dried to optimal moisture levels, and mechanically cleaned to remove any foreign matter. The shells provide natural protection, ensuring the kernels retain their freshness, nutritional value, and rich flavor during transit and storage. These are ideal for snacking, roasting, oil extraction, and industrial processing in global markets.',
        specifications: {
          'Variety': 'Bold / Java / TJ',
          'Moisture': '6-8% Max',
          'Admixture': '1-2% Max',
          'Oil Content': '42-48%',
          'Size (Count per Ounce)': '9/11, 11/13, 13/15',
          'Shell Color': 'Natural tan',
          'Aflatoxin': 'Within EU/US limits',
          'Origin': 'Gujarat, India',
          'Shelf Life': '12 months in proper storage',
        },
        packagingOptions: [
          '25 kg / 50 kg PP woven bags',
          'Jute bags as per buyer specification',
          'Custom retail packaging available',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Each shipment of Peanuts In Shell from AGRITRADE OVERSEAS undergoes multi-stage quality inspection including moisture testing, aflatoxin screening, shell integrity checks, and foreign matter removal. We ensure compliance with international food safety standards including EU, USDA, and FSSAI regulations.',
        metaTitle: 'Peanuts In Shell Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Export-quality Indian Peanuts In Shell from Gujarat. Bold, Java & TJ varieties with premium quality, aflatoxin-tested, and export-ready packaging.',
      },
      {
        name: 'Blanched Peanuts',
        slug: 'blanched-peanuts',
        image: '/images/products/groundnuts/blanched-peanuts.png',
        shortDescription: 'De-skinned and split blanched peanuts with pristine white appearance, ideal for confectionery and food processing.',
        fullDescription: 'AGRITRADE OVERSEAS offers premium Blanched Peanuts processed from the finest Indian groundnut kernels. Our blanching process carefully removes the red skin from high-quality peanut kernels using controlled heat and mechanical methods, resulting in clean, white-skinned peanuts with consistent size and appearance. Blanched peanuts are widely used in confectionery, bakery, peanut butter manufacturing, snack production, and various food processing applications across global markets.',
        specifications: {
          'Type': 'Whole Blanched / Split Blanched',
          'Moisture': '5-7% Max',
          'Admixture': '0.5% Max',
          'Broken Kernels': '2-3% Max',
          'Oil Content': '44-48%',
          'Size (Count per Ounce)': '38/42, 40/50, 50/60, 60/70',
          'Skin Removal': '95-99%',
          'Color': 'Creamy white',
          'Origin': 'Gujarat, India',
          'Shelf Life': '9-12 months',
        },
        packagingOptions: [
          '10 kg / 25 kg vacuum-sealed bags',
          '25 kg / 50 kg PP bags with inner liner',
          'Food-grade carton packaging',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Blanched Peanuts are processed in hygienically maintained facilities with strict HACCP protocols. Every batch undergoes blanching efficiency checks, moisture analysis, microbiological testing, and sensory evaluation before export clearance.',
        metaTitle: 'Blanched Peanuts Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Blanched Peanuts for global food processing and confectionery markets. Whole and split varieties with export-grade quality.',
      },
      {
        name: 'Bold Peanuts',
        slug: 'bold-peanuts',
        image: '/images/products/groundnuts/bold-peanuts.png',
        shortDescription: 'Large-sized bold peanut kernels with rich flavor and high oil content, preferred for direct consumption and oil extraction.',
        fullDescription: 'AGRITRADE OVERSEAS provides top-grade Bold Peanuts (also known as Runner Peanuts) sourced from the prime groundnut-growing regions of Gujarat and Andhra Pradesh. Bold peanuts are characterized by their larger kernel size, uniform shape, reddish-brown skin, and superior oil content. They are the most demanded variety globally for oil extraction, direct eating, roasting, and as raw material in food processing industries. Our bold peanuts are meticulously graded, sortex-cleaned, and quality-tested before shipment.',
        specifications: {
          'Variety': 'Bold / Runner',
          'Moisture': '6-8% Max',
          'Admixture': '1% Max',
          'Oil Content': '44-48%',
          'Size (Count per Ounce)': '38/42, 40/50, 50/60',
          'Kernel Color': 'Reddish brown',
          'Damaged/Shriveled': '2% Max',
          'Origin': 'Gujarat / Andhra Pradesh, India',
          'Shelf Life': '10-12 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP woven bags',
          'Vacuum-sealed bags for premium markets',
          'Jute bags with polythene lining',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Bold Peanuts from AGRITRADE OVERSEAS are hand-picked, sortex-processed, and tested for aflatoxin levels, pesticide residues, and microbiological parameters. We maintain consistent sizing and quality across all shipments to build long-term buyer confidence.',
        metaTitle: 'Bold Peanuts Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Export-quality Indian Bold Peanuts with large kernel size and high oil content. Sortex-cleaned, aflatoxin-tested, and export-ready.',
      },
      {
        name: 'Java Peanuts',
        slug: 'java-peanuts',
        image: '/images/products/groundnuts/java-peanuts.png',
        shortDescription: 'Small-sized Java peanut kernels with sweet taste profile, widely used in confectionery and snack industries globally.',
        fullDescription: 'AGRITRADE OVERSEAS supplies premium Java Peanuts (also known as Spanish-type peanuts) renowned for their smaller kernel size, round shape, and naturally sweet flavor profile. Sourced from select farming regions of Gujarat and Rajasthan, Java peanuts are the preferred variety for confectionery applications, candy coatings, snack manufacturing, and peanut butter production. Their compact size ensures even roasting and consistent flavor development, making them a top choice for food manufacturers worldwide.',
        specifications: {
          'Variety': 'Java / Spanish',
          'Moisture': '6-7% Max',
          'Admixture': '1% Max',
          'Oil Content': '46-50%',
          'Size (Count per Ounce)': '60/70, 70/80, 80/90',
          'Kernel Color': 'Light pink to reddish',
          'Damaged': '2% Max',
          'Origin': 'Gujarat / Rajasthan, India',
          'Shelf Life': '10-12 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Vacuum-sealed packaging for retail',
          'Custom packaging on request',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Java Peanuts undergo rigorous grading for uniform size, moisture content optimization, and comprehensive safety testing including aflatoxin and pesticide residue analysis to ensure they meet the stringent requirements of international confectionery and snack manufacturers.',
        metaTitle: 'Java Peanuts Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Java Peanuts with sweet taste profile for confectionery and snack industries. Small-sized, quality-tested, and export-ready.',
      },
    ],
  },

  // ================================================================
  // 2. SPICES
  // ================================================================
  {
    name: 'Spices',
    slug: 'spices',
    image: '/images/products/spices.png',
    description: 'AGRITRADE OVERSEAS brings the world the finest Indian spices, sourced from the renowned spice-growing regions of Gujarat, Rajasthan, and Madhya Pradesh. Our spice portfolio encompasses the most sought-after varieties including cumin, coriander, fenugreek, fennel, ajwain, turmeric, chilli, and dry ginger — each processed under strict quality controls and certified for international export markets.',
    metaTitle: 'Premium Indian Spices Exporter | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian spices including Cumin, Coriander, Fenugreek, Fennel, Ajwain, Turmeric, Chilli & Dry Ginger. Premium sourcing from Gujarat and Rajasthan.',
    subProducts: [
      {
        name: 'Cumin Seeds',
        slug: 'cumin-seeds',
        image: '/images/products/spices/cumin-seeds.png',
        shortDescription: 'Finest Indian cumin seeds with exceptional aroma and robust flavor, processed under strict quality controls for global markets.',
        fullDescription: 'AGRITRADE OVERSEAS offers top-grade Indian Cumin Seeds (Jeera) renowned worldwide for their distinctive warm aroma, earthy flavor, and superior essential oil content. Sourced from the leading cumin-producing regions of Gujarat and Rajasthan, our cumin seeds undergo rigorous multi-stage cleaning, sortex processing, and quality testing to ensure they meet the expectations of discerning international buyers across the Middle East, Europe, Americas, and Southeast Asia.',
        specifications: {
          'Purity': '95% / 97% / 99% / 99.5%',
          'Moisture': '8-10% Max',
          'Volatile Oil': '2.5-4.5%',
          'Color': 'Greenish-brown to amber',
          'Seed Type': 'Bold / Medium',
          'Admixture': 'As per grade',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Gujarat / Rajasthan, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Jute bags with inner polythene lining',
          'Food-grade packaging available',
          'Private labeling on request',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Each consignment of Cumin Seeds is tested for volatile oil content, purity percentage, moisture levels, and compliance with Singapore/Europe quality standards. We provide SGS and other third-party inspection certificates as required by international buyers.',
        metaTitle: 'Cumin Seeds Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Cumin Seeds from Gujarat with superior aroma and high purity grades. Sortex-processed and export-ready for global markets.',
      },
      {
        name: 'Coriander Seeds',
        slug: 'coriander-seeds',
        image: '/images/products/spices/coriander-seeds.png',
        shortDescription: 'Premium Indian coriander seeds with citrusy aroma and warm flavor, essential for spice blends and food processing worldwide.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium-grade Indian Coriander Seeds sourced from the fertile farmlands of Rajasthan, Gujarat, and Madhya Pradesh. Our coriander seeds are recognized globally for their distinctive citrusy aroma, warm flavor profile, and high essential oil content. Available in both Eagle and Scooter varieties, these seeds serve as essential ingredients in spice blends, curry powders, food processing, and essential oil extraction industries across the globe.',
        specifications: {
          'Variety': 'Eagle / Scooter / Badami',
          'Purity': '95% / 97% / 99%',
          'Moisture': '8-10% Max',
          'Essential Oil': '0.3-0.5%',
          'Color': 'Yellowish-brown',
          'Form': 'Whole seeds / Split',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Rajasthan / Gujarat / MP, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Jute bags with polythene lining',
          'Export-grade food packaging',
          'Private labeling available',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Coriander Seeds undergo comprehensive testing for essential oil content, purity, moisture, and microbiological parameters. Each shipment is accompanied by quality certificates and phytosanitary documentation as required by destination countries.',
        metaTitle: 'Coriander Seeds Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Export-quality Indian Coriander Seeds in Eagle & Scooter varieties. Superior aroma and flavor for global culinary and industrial markets.',
      },
      {
        name: 'Fenugreek Seeds',
        slug: 'fenugreek-seeds',
        image: '/images/products/spices/fenugreek-seeds.png',
        shortDescription: 'Top-quality Indian fenugreek seeds with rich golden color, prized for culinary, pharmaceutical, and nutraceutical applications.',
        fullDescription: 'AGRITRADE OVERSEAS offers premium Indian Fenugreek Seeds (Methi) sourced from the best growing regions of Rajasthan and Gujarat. Our fenugreek seeds are prized for their beautiful golden color, distinctive bitter-sweet flavor profile, and high nutritional content including galactomannan fiber. They serve diverse industries spanning food processing, spice blending, pharmaceutical formulations, nutraceutical supplements, and traditional medicine preparations across global markets.',
        specifications: {
          'Purity': '97% / 98% / 99%',
          'Moisture': '8-10% Max',
          'Color': 'Rich golden / amber',
          'Galactomannan': 'High content',
          'Seed Size': 'Bold / Regular',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Pesticide Residue': 'Compliant with international limits',
          'Origin': 'Rajasthan / Gujarat, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Food-grade sealed packaging',
          'Vacuum-sealed for freshness',
          'Custom packaging on request',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Fenugreek Seeds from AGRITRADE OVERSEAS are tested for purity, moisture, galactomannan content, pesticide residues, and microbiological safety. We ensure every lot meets the quality expectations of pharmaceutical-grade and food-grade buyers.',
        metaTitle: 'Fenugreek Seeds Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Fenugreek Seeds from Gujarat and Rajasthan. High galactomannan content for food, pharmaceutical, and nutraceutical industries.',
      },
      {
        name: 'Fennel Seeds',
        slug: 'fennel-seeds',
        image: '/images/products/spices/fennel-seeds.png',
        shortDescription: 'Aromatic Indian fennel seeds with sweet anise flavor, sourced from Gujarat for culinary and medicinal markets worldwide.',
        fullDescription: 'AGRITRADE OVERSEAS supplies premium-grade Indian Fennel Seeds (Saunf) known for their refreshing sweet-anise aroma and distinctive flavor profile. Sourced from the finest growing regions of Gujarat, our fennel seeds are carefully cleaned, graded by size, and quality-tested for essential oil content. Indian fennel seeds are highly valued in international markets for use in culinary preparations, spice blends, herbal teas, confectionery, digestive formulations, and traditional medicine applications.',
        specifications: {
          'Variety': 'Lucknow / Delhi / Bold',
          'Purity': '97% / 98% / 99%',
          'Moisture': '8-10% Max',
          'Volatile Oil': '1.5-3.5%',
          'Color': 'Greenish to yellowish-green',
          'Seed Size': 'Bold / Medium / Small',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Gujarat, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Food-grade packaging',
          'Retail-ready packaging options',
          'Private labeling on request',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Fennel Seeds are processed and tested for volatile oil content, purity, color retention, and compliance with international food safety standards. We ensure consistent quality and aroma across all shipments.',
        metaTitle: 'Fennel Seeds Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Fennel Seeds with sweet anise aroma from Gujarat. Multiple size grades for culinary, medicinal, and industrial markets.',
      },
      {
        name: 'Ajwain',
        slug: 'ajwain',
        image: '/images/products/spices/ajwain.png',
        shortDescription: 'Premium ajwain (carom seeds) with high thymol content, ideal for pharmaceutical, culinary, and industrial applications.',
        fullDescription: 'AGRITRADE OVERSEAS provides premium-quality Ajwain (Carom Seeds) sourced from the finest growing regions of Rajasthan and Gujarat. Known for their exceptionally high thymol content and distinctive aromatic profile, our ajwain seeds serve both culinary and pharmaceutical markets worldwide. Each batch is carefully processed using advanced cleaning and grading technology to preserve the essential oils and medicinal properties that make Indian ajwain highly sought after by international buyers.',
        specifications: {
          'Purity': '97% / 98% / 99%',
          'Moisture': '8-10% Max',
          'Thymol Content': 'High (>2%)',
          'Color': 'Olive green to brownish',
          'Seed Size': 'Bold / Regular',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Pesticide Residue': 'Compliant with international limits',
          'Origin': 'Rajasthan / Gujarat, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Food-grade export packaging',
          'Vacuum-sealed options available',
          'Custom packaging for retail markets',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Ajwain from AGRITRADE OVERSEAS undergoes thorough testing for thymol content, purity, moisture levels, and pesticide residue analysis. We ensure pharmaceutical-grade quality for the most demanding international markets.',
        metaTitle: 'Ajwain (Carom Seeds) Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Export-quality Indian Ajwain with high thymol content. Premium sourcing for pharmaceutical and culinary markets worldwide.',
      },
      {
        name: 'Turmeric Finger',
        slug: 'turmeric-finger',
        image: '/images/products/spices/turmeric-finger.png',
        shortDescription: 'High-curcumin Indian turmeric fingers with vibrant golden color, essential for food, pharmaceutical, and cosmetic industries.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium Indian Turmeric Fingers sourced from the renowned turmeric-growing regions of Andhra Pradesh, Telangana, and Maharashtra. Our turmeric fingers are prized for their high curcumin content, vibrant golden-orange color, and pungent earthy flavor. Indian turmeric is the world\'s most sought-after variety, used extensively in food coloring, spice blends, pharmaceutical formulations, nutraceutical supplements, and cosmetic products across international markets.',
        specifications: {
          'Variety': 'Rajapore / Salem / Erode / Nizamabad',
          'Curcumin Content': '3-5%',
          'Moisture': '10-12% Max',
          'Color Value': 'High — Vibrant golden-orange',
          'Form': 'Whole fingers / Bulbs',
          'Polished': 'Yes / Unpolished available',
          'Machine Cleaned': 'Yes',
          'Origin': 'Andhra Pradesh / Maharashtra, India',
          'Shelf Life': '12-24 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Jute bags with inner lining',
          'Export-grade food packaging',
          'Custom packaging available',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Turmeric Fingers are tested for curcumin percentage, color value, moisture, lead content, and microbiological parameters. We guarantee consistent quality with batch-specific test reports for every shipment.',
        metaTitle: 'Turmeric Finger Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Turmeric Fingers with high curcumin content. Vibrant golden color for food, pharmaceutical, and cosmetic industries.',
      },
      {
        name: 'Chilli',
        slug: 'chilli',
        image: '/images/products/spices/chilli.png',
        shortDescription: 'Premium Indian dried red chillies with intense color and heat, available in multiple varieties for global food industries.',
        fullDescription: 'AGRITRADE OVERSEAS supplies premium dried Red Chillies sourced from India\'s leading chilli-growing states including Andhra Pradesh, Karnataka, and Madhya Pradesh. India is the world\'s largest producer and exporter of dried chillies, and our offerings include popular varieties known for their intense red color, pungent heat, and rich flavor. Our chillies cater to diverse applications including spice powders, curry pastes, food coloring, oleoresin extraction, and direct culinary use in markets worldwide.',
        specifications: {
          'Variety': 'Teja / S17 / Byadgi / Guntur / Kashmiri',
          'Moisture': '10-12% Max',
          'Heat Level (SHU)': 'Varies by variety (5,000-100,000+)',
          'Color Value (ASTA)': 'Varies by variety',
          'Form': 'Whole dried / Stemless / Stemcut',
          'Machine Cleaned': 'Yes',
          'Aflatoxin': 'Within permissible limits',
          'Origin': 'Andhra Pradesh / Karnataka / MP, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '10 kg / 25 kg / 50 kg PP bags',
          'Food-grade carton packaging',
          'Vacuum-sealed options',
          'Custom packaging on request',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Red Chillies from AGRITRADE OVERSEAS undergo testing for heat value (Scoville scale), ASTA color value, moisture content, aflatoxin levels, and pesticide residues. We ensure consistent quality matching buyer specifications for each variety.',
        metaTitle: 'Dried Red Chilli Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian dried Red Chillies in Teja, S17, Byadgi & Kashmiri varieties. Intense color and heat for global food industries.',
      },
      {
        name: 'Dry Ginger',
        slug: 'dry-ginger',
        image: '/images/products/spices/dry-ginger.png',
        shortDescription: 'High-quality Indian dry ginger with pungent aroma and strong flavor, used in food processing and pharmaceutical industries.',
        fullDescription: 'AGRITRADE OVERSEAS provides premium-quality Dry Ginger (Sonth/Sunthi) sourced from Kerala, Karnataka, and Northeastern India. Indian dry ginger is valued globally for its strong pungent aroma, spicy flavor, and high gingerol content. Our dry ginger undergoes careful drying, cleaning, and grading processes to ensure optimal quality retention. It is widely used in spice blends, ginger powder manufacturing, beverage formulations, pharmaceutical preparations, and traditional Ayurvedic medicine applications.',
        specifications: {
          'Variety': 'Cochin / Calicut / Nadia',
          'Moisture': '10-12% Max',
          'Volatile Oil': '1.5-3%',
          'Gingerol Content': 'High',
          'Color': 'Light brown to pale yellow',
          'Form': 'Whole / Split / Bleached / Unbleached',
          'Machine Cleaned': 'Yes',
          'Origin': 'Kerala / Karnataka, India',
          'Shelf Life': '12-24 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Jute bags with polythene lining',
          'Food-grade export packaging',
          'Custom packaging available',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Dry Ginger is tested for volatile oil content, gingerol levels, moisture, microbiological safety, and pesticide residues. We provide comprehensive quality documentation including certificates of analysis for every shipment.',
        metaTitle: 'Dry Ginger Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Dry Ginger with high gingerol content. Strong aroma and flavor for food processing and pharmaceutical industries.',
      },
    ],
  },

  // ================================================================
  // 3. PULSES
  // ================================================================
  {
    name: 'Pulses',
    slug: 'pulses',
    image: '/images/products/pulses.png',
    description: 'AGRITRADE OVERSEAS is a reliable exporter of premium Indian pulses, offering a diverse range of protein-rich legumes sourced from India\'s major pulse-producing regions. Our pulse portfolio includes chickpeas, green moong, gram, and soyabeans — all carefully cleaned, graded, and packaged to meet the nutritional needs and quality expectations of international food markets.',
    metaTitle: 'Premium Indian Pulses Exporter | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian pulses including Chickpeas, Desi Chickpeas, Green Moong, Gram & Soyabeans. Premium quality for global food markets.',
    subProducts: [
      {
        name: 'Chickpeas',
        slug: 'chickpeas',
        image: '/images/products/pulses/chickpeas.png',
        shortDescription: 'Premium Kabuli chickpeas with large kernel size, high protein content, and excellent cooking quality for global food markets.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium-grade Kabuli Chickpeas sourced from India\'s leading chickpea-growing regions of Madhya Pradesh, Rajasthan, and Maharashtra. Our Kabuli chickpeas are distinguished by their large, cream-colored kernels, smooth texture, and superior cooking quality. Rich in protein, dietary fiber, and essential minerals, these chickpeas are ideal for hummus production, salads, canning, ready-to-eat meals, and direct retail sale in health-conscious international markets.',
        specifications: {
          'Type': 'Kabuli',
          'Size': '7mm / 8mm / 9mm / 10mm / 12mm+',
          'Moisture': '10-12% Max',
          'Protein': '18-22%',
          'Color': 'Cream / Beige',
          'Admixture': '1-2% Max',
          'Damaged': '1-2% Max',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Madhya Pradesh / Rajasthan, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Jute bags with inner lining',
          'Food-grade retail packaging',
          'Custom branding available',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Kabuli Chickpeas are size-graded using precision machinery, moisture-optimized, and tested for protein content, cooking quality, and food safety parameters. We provide full documentation including phytosanitary and fumigation certificates.',
        metaTitle: 'Kabuli Chickpeas Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Kabuli Chickpeas in multiple size grades. High protein, sortex-cleaned, and export-ready for global food markets.',
      },
      {
        name: 'Desi Chickpeas',
        slug: 'desi-chickpeas',
        image: '/images/products/pulses/desi-chickpeas.png',
        shortDescription: 'Traditional Desi chickpeas with robust nutty flavor and high nutritional value, staple in South Asian and Middle Eastern cuisines.',
        fullDescription: 'AGRITRADE OVERSEAS supplies premium Desi Chickpeas (Chana) — the traditional Indian chickpea variety with a rough outer coat, darker color, and distinctively robust nutty flavor. Sourced from the heartlands of Madhya Pradesh and Rajasthan, Desi chickpeas are nutritional powerhouses rich in protein, complex carbohydrates, and dietary fiber. They are the primary ingredient for besan (gram flour), chana dal, and countless traditional dishes across South Asian, Middle Eastern, and African cuisines.',
        specifications: {
          'Type': 'Desi / Brown Chana',
          'Size': '6mm / 7mm / 8mm',
          'Moisture': '10-12% Max',
          'Protein': '20-24%',
          'Color': 'Brown / Dark tan',
          'Admixture': '1-2% Max',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Madhya Pradesh / Rajasthan, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Jute bags as per buyer requirement',
          'Retail packaging available',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Desi Chickpeas from AGRITRADE OVERSEAS are cleaned, graded by size, and tested for protein content, moisture, insect damage, and microbiological safety. We ensure consistent quality for flour mills and food processing clients.',
        metaTitle: 'Desi Chickpeas Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Desi Chickpeas with high protein content. Traditional variety for gram flour, chana dal, and global food markets.',
      },
      {
        name: 'Green Moong',
        slug: 'green-moong',
        image: '/images/products/pulses/green-moong.png',
        shortDescription: 'Premium whole green moong beans with high germination rate, ideal for cooking, sprouting, and health food applications.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium Green Moong Beans (Mung Beans) sourced from Rajasthan, Madhya Pradesh, and Maharashtra. Green moong is one of the most versatile and nutritious pulses, valued for its easy digestibility, high protein content, and excellent sprouting properties. Our green moong beans are carefully cleaned, size-graded, and quality-tested for consistent germination rates. They serve diverse applications including direct cooking, sprouting, mung bean noodle production, and health food manufacturing.',
        specifications: {
          'Type': 'Whole Green Moong',
          'Size': '3.5mm / 4mm / 4.5mm+',
          'Moisture': '10-12% Max',
          'Protein': '22-25%',
          'Color': 'Bright olive green',
          'Admixture': '1% Max',
          'Germination Rate': '90%+',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Rajasthan / MP / Maharashtra, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Food-grade sealed packaging',
          'Retail-ready packaging',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Green Moong Beans are tested for germination rate, protein content, moisture, color consistency, and food safety compliance. We ensure bright green color and high sprouting quality for health-conscious international markets.',
        metaTitle: 'Green Moong Beans Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Green Moong Beans with high protein and germination rate. Quality-tested for cooking, sprouting, and health food markets.',
      },
      {
        name: 'Gram',
        slug: 'gram',
        image: '/images/products/pulses/gram.png',
        shortDescription: 'High-quality Bengal gram (chana dal) with consistent sizing and rich protein content for food processing and retail markets.',
        fullDescription: 'AGRITRADE OVERSEAS provides premium Bengal Gram (Chana Dal) — the split and polished form of desi chickpeas — sourced from major producing regions across central India. Bengal gram is one of India\'s most important pulse crops and a staple protein source in diets across South Asia, the Middle East, and Africa. Our gram is carefully processed through dehulling, splitting, and polishing operations to produce uniform, clean, golden-yellow dal ideal for direct cooking, snack production, and flour manufacturing.',
        specifications: {
          'Type': 'Split Bengal Gram / Chana Dal',
          'Moisture': '10-12% Max',
          'Protein': '20-24%',
          'Color': 'Golden yellow',
          'Admixture': '1% Max',
          'Broken/Damaged': '2% Max',
          'Polished': 'Yes / Oil polished / Dry polished',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Madhya Pradesh / Rajasthan, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Retail packaging (1kg / 5kg)',
          'Custom branding available',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Bengal Gram from AGRITRADE OVERSEAS undergoes precision dehulling, polishing, and sortex cleaning. Each batch is tested for protein, moisture, uniformity, and microbiological safety parameters.',
        metaTitle: 'Bengal Gram Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Bengal Gram (Chana Dal) with high protein content. Split, polished, and export-ready for global food markets.',
      },
      {
        name: 'Soyabeans',
        slug: 'soyabeans',
        image: '/images/products/pulses/soyabeans.png',
        shortDescription: 'Non-GMO Indian soyabeans with high protein and oil content, serving food processing and animal feed industries globally.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium non-GMO Indian Soyabeans sourced from Madhya Pradesh, Maharashtra, and Rajasthan — India\'s soybean heartland. Indian soyabeans are valued globally for their high protein content, favorable oil composition, and non-GMO status. Our soyabeans serve diverse industries including soy oil extraction, soy meal production, tofu manufacturing, soy milk production, textured vegetable protein (TVP), and animal feed formulation in international markets.',
        specifications: {
          'Type': 'Non-GMO Indian Soyabeans',
          'Moisture': '10-12% Max',
          'Protein': '38-42%',
          'Oil Content': '18-20%',
          'Color': 'Light yellow',
          'Admixture': '1-2% Max',
          'Damaged': '2% Max',
          'GMO Status': 'Non-GMO',
          'Origin': 'Madhya Pradesh / Maharashtra, India',
          'Shelf Life': '10-12 months',
        },
        packagingOptions: [
          '50 kg PP bags',
          'Bulk vessel shipments',
          'Container loads: 20 ft / 40 ft FCL',
          'Custom packaging available',
        ],
        exportQuality: 'Our Soyabeans are tested for protein percentage, oil content, moisture, GMO-free certification, and compliance with international food and feed safety standards. We provide full traceability from farm to port.',
        metaTitle: 'Non-GMO Soyabeans Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium non-GMO Indian Soyabeans with high protein and oil content. Quality-tested for food processing and animal feed industries.',
      },
    ],
  },

  // ================================================================
  // 4. SESAME SEEDS
  // ================================================================
  {
    name: 'Sesame Seeds',
    slug: 'sesame-seeds',
    image: '/images/products/sesame-seeds.png',
    description: 'AGRITRADE OVERSEAS is a leading exporter of premium Indian sesame seeds, offering natural white, black, and hulled varieties processed to the highest quality standards. Sourced from Gujarat, Rajasthan, and Madhya Pradesh, our sesame seeds are prized globally for their superior oil content, rich flavor, and nutritional profile — serving bakery, confectionery, tahini, oil extraction, and health food markets worldwide.',
    metaTitle: 'Premium Sesame Seeds Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian Sesame Seeds in Natural White, Black, and Hulled varieties. Premium quality for bakery, tahini, and health food markets.',
    subProducts: [
      {
        name: 'Natural White Sesame Seeds',
        slug: 'natural-white-sesame-seeds',
        image: '/images/products/sesame-seeds/natural-white-sesame-seeds.png',
        shortDescription: 'Premium natural white sesame seeds with high oil content and clean flavor, ideal for bakery, tahini, and oil extraction.',
        fullDescription: 'AGRITRADE OVERSEAS supplies premium Natural White Sesame Seeds sourced from the finest growing regions of Gujarat and Rajasthan. Our white sesame seeds are prized for their high oil content (48-52%), clean nutty flavor, and uniform creamy-white appearance. These are the most versatile sesame variety, widely used in bakery products, tahini paste, sesame oil production, confectionery, health bars, and as a garnishing ingredient in cuisines worldwide.',
        specifications: {
          'Type': 'Natural White (Unhulled)',
          'Purity': '99% / 99.5% / 99.9%',
          'Moisture': '5-6% Max',
          'Oil Content': '48-52%',
          'FFA (Free Fatty Acid)': '1-2% Max',
          'Color': 'Creamy white / Off-white',
          'Admixture': 'As per grade',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Gujarat / Rajasthan, India',
          'Shelf Life': '12 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Food-grade kraft paper bags',
          'Vacuum-sealed packaging',
          'Custom packaging on request',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Each lot of Natural White Sesame Seeds is tested for oil content, FFA levels, purity, moisture, Salmonella, and pesticide residues. We maintain stringent quality controls to meet Japanese, Korean, European, and Middle Eastern market specifications.',
        metaTitle: 'Natural White Sesame Seeds Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Natural White Sesame Seeds with high oil content. Sortex-cleaned for bakery, tahini, and oil extraction markets.',
      },
      {
        name: 'Black Sesame Seeds',
        slug: 'black-sesame-seeds',
        image: '/images/products/sesame-seeds/black-sesame-seeds.png',
        shortDescription: 'Nutrient-rich black sesame seeds with intense flavor and high antioxidant content, valued in Asian cuisines and health foods.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium Black Sesame Seeds sourced from select farming regions of Gujarat, Rajasthan, and West Bengal. Black sesame seeds are nutritional powerhouses, rich in calcium, iron, antioxidants, and essential fatty acids. Their deep black color, intense nutty flavor, and crunchy texture make them highly valued in East Asian cuisines, traditional medicine, health food products, bakery items, and premium confectionery across international markets.',
        specifications: {
          'Type': 'Black (Unhulled)',
          'Purity': '98% / 99% / 99.5%',
          'Moisture': '5-6% Max',
          'Oil Content': '46-50%',
          'Color': 'Deep jet black',
          'Admixture': 'As per grade',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Gujarat / Rajasthan / West Bengal, India',
          'Shelf Life': '12 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags',
          'Food-grade packaging',
          'Vacuum-sealed options',
          'Retail-ready packaging available',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Black Sesame Seeds undergo color sorting to remove off-colored seeds, followed by comprehensive testing for oil content, purity, moisture, and food safety parameters including heavy metals and pesticide residues.',
        metaTitle: 'Black Sesame Seeds Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Black Sesame Seeds with high antioxidant content. Deep black color and intense flavor for Asian cuisines and health food markets.',
      },
      {
        name: 'Hulled Sesame Seeds',
        slug: 'hulled-sesame-seeds',
        image: '/images/products/sesame-seeds/hulled-sesame-seeds.png',
        shortDescription: 'Premium hulled sesame seeds with pristine white appearance and mild flavor, perfect for bakery, confectionery, and tahini production.',
        fullDescription: 'AGRITRADE OVERSEAS offers premium Hulled Sesame Seeds produced from carefully selected Indian white sesame seeds through a specialized hulling process that removes the outer seed coat. The result is pure, pristine white seeds with a smooth texture, mild sweet-nutty flavor, and extended shelf life. Hulled sesame seeds are the premium choice for tahini paste manufacturing, hamburger bun toppings, sushi garnishing, confectionery coatings, halva production, and bakery applications in the most demanding international markets.',
        specifications: {
          'Type': 'Hulled (Skin removed)',
          'Purity': '99.5% / 99.9%',
          'Moisture': '4-5% Max',
          'Oil Content': '50-55%',
          'FFA': '1% Max',
          'Color': 'Pure white',
          'Broken Seeds': '1% Max',
          'Machine Cleaned': 'Yes — Color sorted',
          'Origin': 'Gujarat, India',
          'Shelf Life': '6-9 months',
        },
        packagingOptions: [
          '25 kg / 50 kg PP bags with inner liner',
          'Vacuum-sealed packaging (recommended)',
          'Food-grade carton packaging',
          'Custom packaging on request',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Hulled Sesame Seeds from AGRITRADE OVERSEAS are produced under strict hygienic conditions with HACCP protocols. Every batch is tested for whiteness index, FFA, Salmonella, E. coli, and aflatoxin to meet the most stringent food safety requirements.',
        metaTitle: 'Hulled Sesame Seeds Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Premium Indian Hulled Sesame Seeds with pristine white appearance. High purity for tahini, bakery, and confectionery industries.',
      },
    ],
  },

  // ================================================================
  // 5. GRAINS
  // ================================================================
  {
    name: 'Grains',
    slug: 'grains',
    image: '/images/products/grains.png',
    description: 'AGRITRADE OVERSEAS exports premium Indian grains including wheat and rice — the foundational staples of global food systems. Sourced from India\'s most productive agricultural regions, our grains are carefully cleaned, graded, and quality-tested to meet the exacting standards of international flour mills, rice processors, food manufacturers, and institutional buyers worldwide.',
    metaTitle: 'Premium Indian Grains Exporter — Wheat & Rice | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian Wheat and Rice for global food industries. Premium varieties, quality-tested, and packaged for international markets.',
    subProducts: [
      {
        name: 'Wheat',
        slug: 'wheat',
        image: '/images/products/grains/wheat.png',
        shortDescription: 'High-grade Indian wheat varieties ideal for milling, baking, and food processing industries across international markets.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium Indian Wheat sourced from the major wheat-producing states of Punjab, Haryana, Madhya Pradesh, and Uttar Pradesh. Our wheat varieties are selected for their superior milling quality, high protein content, and excellent baking characteristics. We supply Sharbati, Lokwan, and Durum wheat varieties to flour mills, bakeries, pasta manufacturers, and food processing industries across the globe, ensuring consistent quality with every shipment backed by comprehensive test reports.',
        specifications: {
          'Variety': 'Sharbati / Lokwan / Durum / MP Wheat',
          'Moisture': '12-14% Max',
          'Protein': '10-13%',
          'Gluten': '8-10%',
          'Color': 'Golden amber',
          'Admixture': '1-2% Max',
          'Damaged/Shriveled': '2% Max',
          'Machine Cleaned': 'Yes',
          'Origin': 'Punjab / Haryana / MP, India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '50 kg PP bags',
          'Jute bags with food-grade lining',
          'Bulk vessel shipments available',
          'Custom packaging options',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Wheat is tested for protein content, gluten quality, falling number, moisture, hectolitre weight, and pesticide residues. We ensure milling-grade quality meeting the specifications of international flour mills and food processors.',
        metaTitle: 'Premium Wheat Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Export-quality Indian Wheat in Sharbati, Lokwan & Durum varieties. High protein, superior milling quality for global food industries.',
      },
      {
        name: 'Rice',
        slug: 'rice',
        image: '/images/products/grains/rice.png',
        shortDescription: 'Premium Indian rice varieties including Basmati and non-Basmati, prized for exceptional aroma, grain length, and cooking quality.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium Indian Rice in both Basmati and Non-Basmati varieties to meet the diverse requirements of global rice markets. Indian rice is renowned worldwide for its exceptional aroma, long grain length, fluffy texture, and superior cooking quality. Our Basmati rice varieties offer the signature fragrance and elongation that make Indian rice the most sought-after in international markets, while our non-Basmati varieties provide excellent quality at competitive pricing for bulk food markets.',
        specifications: {
          'Variety': 'Basmati (1121/1509/Pusa) / Non-Basmati (IR-64/Sona Masuri)',
          'Grain Length': '7.0mm+ (Basmati) / 5.5mm+ (Non-Basmati)',
          'Moisture': '12-14% Max',
          'Broken': '1% / 5% / 10% / 25% (as per grade)',
          'Color': 'Creamy white / Golden (parboiled)',
          'Aroma': 'Strong natural fragrance (Basmati)',
          'Cooking Elongation': '2x+ (Basmati)',
          'Machine Cleaned': 'Yes — Color sorted',
          'Origin': 'Punjab / Haryana / UP / West Bengal, India',
          'Shelf Life': '18-24 months',
        },
        packagingOptions: [
          '5 kg / 10 kg / 25 kg / 50 kg PP/Non-woven bags',
          'Jute bags for bulk shipments',
          'Branded retail packaging',
          'Custom packaging and labeling',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Rice undergoes multi-stage quality assessment including grain length measurement, broken percentage analysis, moisture testing, aroma evaluation, and cooking test. We provide comprehensive certificates of analysis and origin documentation.',
        metaTitle: 'Premium Rice Exporter from India — Basmati & Non-Basmati | AGRITRADE OVERSEAS',
        metaDescription: 'Export-quality Indian Rice including Basmati 1121, 1509, Pusa, Sona Masuri. Premium aroma, long grain, and superior cooking quality.',
      },
    ],
  },

  // ================================================================
  // 6. DRY FRUITS
  // ================================================================
  {
    name: 'Dry Fruits',
    slug: 'dry-fruits',
    image: '/images/products/dry-fruits.png',
    description: 'AGRITRADE OVERSEAS supplies premium Indian dry fruits for international markets, starting with our high-quality raisin offerings. Sourced from the renowned grape-growing regions of Maharashtra and Karnataka, our dry fruits are carefully processed, graded, and packaged to deliver consistent quality and natural sweetness to confectionery, bakery, and snack food industries worldwide.',
    metaTitle: 'Premium Indian Dry Fruits Exporter | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian Dry Fruits including premium Raisins. Naturally sweet, quality-tested, and packaged for global food markets.',
    subProducts: [
      {
        name: 'Raisins',
        slug: 'raisins',
        image: '/images/products/dry-fruits/raisins.png',
        shortDescription: 'Premium Indian raisins with natural sweetness and rich flavor, sourced from Maharashtra\'s finest vineyards for global markets.',
        fullDescription: 'AGRITRADE OVERSEAS exports premium Indian Raisins (Kishmish) produced from the finest grape varieties grown in Maharashtra\'s Nashik and Sangli regions — India\'s grape capital. Our raisins are naturally sun-dried or mechanically dried to preserve their natural sweetness, rich flavor, and nutritional value. Available in golden, green, and brown varieties, our raisins serve bakery, confectionery, cereal, snack food, and health food industries in international markets seeking consistent quality and competitive pricing.',
        specifications: {
          'Variety': 'Indian / Thompson Seedless',
          'Type': 'Golden / Green / Brown',
          'Moisture': '14-16% Max',
          'Sugar Content': '65-72%',
          'Size': 'Small / Medium / Jumbo',
          'Color': 'Golden yellow / Green / Dark brown',
          'SO2 (if applicable)': 'Within permissible limits',
          'Machine Cleaned': 'Yes — Sortex processed',
          'Origin': 'Maharashtra (Nashik/Sangli), India',
          'Shelf Life': '12-18 months',
        },
        packagingOptions: [
          '10 kg / 15 kg carton boxes',
          '25 kg / 50 kg PP bags',
          'Vacuum-sealed for freshness',
          'Retail-ready packaging (250g/500g/1kg)',
          'Container loads: 20 ft / 40 ft FCL',
        ],
        exportQuality: 'Our Raisins undergo thorough cleaning, stem removal, sortex processing, and testing for moisture, sugar content, SO2 levels (where applicable), and microbiological safety. We ensure compliance with EU, US, and Gulf food safety regulations.',
        metaTitle: 'Premium Raisins Exporter from India | AGRITRADE OVERSEAS',
        metaDescription: 'Export-quality Indian Raisins from Maharashtra. Golden, green & brown varieties with natural sweetness for bakery and confectionery markets.',
      },
    ],
  },
];

// ===== HELPER FUNCTIONS =====

export function getCategoryBySlug(slug: string): ProductCategory | undefined {
  return productCategories.find((cat) => cat.slug === slug);
}

export function getSubProductBySlug(
  categorySlug: string,
  productSlug: string
): { category: ProductCategory; product: SubProduct } | undefined {
  const category = getCategoryBySlug(categorySlug);
  if (!category) return undefined;
  const product = category.subProducts.find((p) => p.slug === productSlug);
  if (!product) return undefined;
  return { category, product };
}

export function getAllCategorySlugs(): string[] {
  return productCategories.map((cat) => cat.slug);
}

export function getAllSubProductParams(): { category: string; product: string }[] {
  const params: { category: string; product: string }[] = [];
  productCategories.forEach((cat) => {
    cat.subProducts.forEach((prod) => {
      params.push({ category: cat.slug, product: prod.slug });
    });
  });
  return params;
}

export function getAllSubProducts(): { categoryName: string; categorySlug: string; product: SubProduct }[] {
  const all: { categoryName: string; categorySlug: string; product: SubProduct }[] = [];
  productCategories.forEach((cat) => {
    cat.subProducts.forEach((prod) => {
      all.push({ categoryName: cat.name, categorySlug: cat.slug, product: prod });
    });
  });
  return all;
}
